In [6]:
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

In [7]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [8]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()

In [9]:
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Ahmedabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [10]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Ahmedabad, Gujarat')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [12]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(1)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[1]')
hat.click()

In [13]:
for i in range(0,750):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [14]:
hatch_url = []
hatch = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in hatch:
    hatch_url.append(i.get_attribute('href'))
len(hatch_url)

246

In [15]:
price = []
year = []
make = []
model = []
fuel = []
trans = []
location = []
mile = []
color = []
owner =[]
engine = []
seating = []

for link in hatch_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        price.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        price.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        year.append(yea.text)
    except NoSuchElementException:
        year.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        make.append(mak.text)
    except NoSuchElementException:
        make.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        fuel.append(fu.text)
    except NoSuchElementException:
        fuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        trans.append(tr.text)
    except NoSuchElementException:
        trans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        model.append(mod.text)
    except NoSuchElementException:
        model.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        mile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        mile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        color.append(col.text)
    except NoSuchElementException:
        color.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        owner.append(own.text)
    except NoSuchElementException:
        owner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        engine.append(eng.text)
    except NoSuchElementException:
        engine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        seating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        seating.append('-')

In [16]:
hatch_ahm = pd.DataFrame({})
hatch_ahm['price'] = price
hatch_ahm['year'] = year
hatch_ahm['make'] = make
hatch_ahm['model'] = model
hatch_ahm['fuel'] = fuel
hatch_ahm['trans'] = trans
hatch_ahm['location'] = location
hatch_ahm['mile'] = mile
hatch_ahm['color'] = color
hatch_ahm['owner'] = owner
hatch_ahm['engine'] = engine
hatch_ahm['seating'] = seating
hatch_ahm.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,5.9,Jun 2018,Volkswagen,Polo,Petrol,Manual,Ahmedabad,61982,Red,First,"1198 cc, 3 Cylinders Inline, 4 Valves/Cylinder...",5
1,7.25,Jun 2018,Maruti Suzuki,Swift,Diesel,Automatic,Ahmedabad,35387,White,First,"1248 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
2,2.25,May 2013,Hyundai,Eon,Petrol,Manual,Ahmedabad,51600,Grey,Second,"814 cc, 3 Cylinders Inline, 3 Valves/Cylinder,...",5
3,3.25,Jul 2013,Volkswagen,Polo,Diesel,Manual,Ahmedabad,65000,Silver,First,"1199 cc, 3 Cylinders Inline, 4 Valves/Cylinder...",5
4,6.25,Mar 2017,Hyundai,Elite i20,Diesel,Manual,Ahmedabad,56000,White,First,"1396 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [17]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [18]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Ahmedabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(4)

In [19]:
#time.sleep(25)
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Ahmedabad, Gujarat')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [21]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[3]/span[1]')
hat.click()

In [22]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [23]:
suv_url = []
suv = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in suv:
    suv_url.append(i.get_attribute('href'))
len(suv_url)

248

In [24]:
sprice = []
syear = []
smake = []
smodel = []
sfuel = []
strans = []
slocation = []
smile = []
scolor = []
sowner =[]
sengine = []
sseating = []

for link in suv_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        syear.append(yea.text)
    except NoSuchElementException:
        syear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        smake.append(mak.text)
    except NoSuchElementException:
        smake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sfuel.append(fu.text)
    except NoSuchElementException:
        sfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        strans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        slocation.append(loc.text)
    except NoSuchElementException:
        slocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        smodel.append(mod.text)
    except NoSuchElementException:
        smodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        smile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        smile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        scolor.append(col.text)
    except NoSuchElementException:
        scolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sowner.append(own.text)
    except NoSuchElementException:
        sowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sengine.append(eng.text)
    except NoSuchElementException:
        sengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sseating.append('-')

In [25]:
suv_ahm = pd.DataFrame({})
suv_ahm['price'] = sprice
suv_ahm['year'] = syear
suv_ahm['make'] = smake
suv_ahm['model'] = smodel
suv_ahm['fuel'] = sfuel
suv_ahm['trans'] = strans
suv_ahm['location'] = slocation
suv_ahm['mile'] = smile
suv_ahm['color'] = scolor
suv_ahm['owner'] = sowner
suv_ahm['engine'] = sengine
suv_ahm['seating'] = sseating
suv_ahm.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,21,Jun 2014,Land Rover,Freelander,Diesel,Automatic,Ahmedabad,77654,Black,First,"2179 cc, 4 Cylinders Inline, 4 Valves/Cylinder",5
1,7.5,May 2017,Ford,Ecosport,Diesel,Manual,Ahmedabad,71000,Silver,First,"1498 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
2,45,Oct 2018,Mercedes-Benz,GLC,Petrol,Automatic,Ahmedabad,15000,Blue,First,"1991 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
3,65,Apr 2019,Audi,Q7,Diesel,Automatic,Ahmedabad,22000,Silver,First,"2967 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",7
4,5.25,Jun 2013,Mahindra,Scorpio,Diesel,Manual,Ahmedabad,98013,White,Second,"2179 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7 & 9

In [26]:
hatch_ahm['Body'] = 'hatchback'
suv_ahm['Body'] = 'SUV'

In [27]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Chennai')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(10)

In [28]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Ahmedabad, Gujarat')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(15)

In [30]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[7]/span[1]')
hat.click()

In [34]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(1)
    driver.execute_script("window.scrollBy(0,-500)")

In [35]:
sdn_url = []
sdn = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in sdn:
    sdn_url.append(i.get_attribute('href'))
len(sdn_url)

246

In [36]:
sdprice = []
sdyear = []
sdmake = []
sdmodel = []
sdfuel = []
sdtrans = []
sdlocation = []
sdmile = []
sdcolor = []
sdowner =[]
sdengine = []
sdseating = []

for link in sdn_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sdprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sdprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        sdyear.append(yea.text)
    except NoSuchElementException:
        sdyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        sdmake.append(mak.text)
    except NoSuchElementException:
        sdmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sdfuel.append(fu.text)
    except NoSuchElementException:
        sdfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        sdtrans.append(tr.text)
    except NoSuchElementException:
        sdtrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        sdlocation.append(loc.text)
    except NoSuchElementException:
        sdlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        sdmodel.append(mod.text)
    except NoSuchElementException:
        sdmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        sdmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        sdmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        sdcolor.append(col.text)
    except NoSuchElementException:
        sdcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sdowner.append(own.text)
    except NoSuchElementException:
        sdowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sdengine.append(eng.text)
    except NoSuchElementException:
        sdengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sdseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sdseating.append('-')

In [37]:
sdn_ahm = pd.DataFrame({})
sdn_ahm['price'] = sdprice
sdn_ahm['year'] = sdyear
sdn_ahm['make'] = sdmake
sdn_ahm['model'] = sdmodel
sdn_ahm['fuel'] = sdfuel
sdn_ahm['trans'] = sdtrans
sdn_ahm['location'] = sdlocation
sdn_ahm['mile'] = sdmile
sdn_ahm['color'] = sdcolor
sdn_ahm['owner'] = sdowner
sdn_ahm['engine'] = sdengine
sdn_ahm['seating'] = sdseating
sdn_ahm['Body'] = 'sedan'
sdn_ahm.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,16.9,Mar 2016,BMW,3-Series,Diesel,Automatic,Ahmedabad,45000,Grey,Second,"1995 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
1,27.5,May 2016,Mercedes-Benz,C-Class,Diesel,Automatic,Ahmedabad,73000,Blue,First,"2143 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
2,3.75,Apr 2013,Chevrolet,Cruze,Diesel,Manual,Ahmedabad,60700,White,Third,"1998 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
3,6.75,Apr 2015,Maruti Suzuki,Ciaz,Petrol,Automatic,Ahmedabad,38000,White,First,"1373 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
4,46.5,Jan 2020,Mercedes-Benz,C-Class,Diesel,Automatic,Ahmedabad,9000,Red,UnRegistered Car,"2143 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan

In [38]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Ahmedabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(20)

In [40]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Ahmedabad, Gujarat')
time.sleep(10)
srch.send_keys(Keys.ENTER)
time.sleep(10)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [41]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[4]/span[1]')
hat.click()

In [42]:
for i in range(0,20):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [43]:
van_url = []
van = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in van:
    van_url.append(i.get_attribute('href'))
len(van_url)

24

In [44]:
vprice = []
vyear = []
vmake = []
vmodel = []
vfuel = []
vtrans = []
vlocation = []
vmile = []
vcolor = []
vowner =[]
vengine = []
vseating = []

for link in van_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        vprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        vprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        vyear.append(yea.text)
    except NoSuchElementException:
        vyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        vmake.append(mak.text)
    except NoSuchElementException:
        vmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        vfuel.append(fu.text)
    except NoSuchElementException:
        vfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        vtrans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        vlocation.append(loc.text)
    except NoSuchElementException:
        vlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        vmodel.append(mod.text)
    except NoSuchElementException:
        vmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        vmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        vmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        vcolor.append(col.text)
    except NoSuchElementException:
        vcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        vowner.append(own.text)
    except NoSuchElementException:
        vowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        vengine.append(eng.text)
    except NoSuchElementException:
        vengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        vseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        vseating.append('-')

In [64]:
#vtrans = vtrans.append('Manual')

In [46]:
van_ahm = pd.DataFrame({})
van_ahm['price'] = vprice
van_ahm['year'] = vyear
van_ahm['make'] = vmake
van_ahm['model'] = vmodel
van_ahm['fuel'] = vfuel
van_ahm['trans'] = vtrans
van_ahm['location'] = vlocation
van_ahm['mile'] = vmile
van_ahm['color'] = vcolor
van_ahm['owner'] = vowner
van_ahm['engine'] = vengine
van_ahm['seating'] = vseating
van_ahm['Body'] = 'minivan'
van_ahm.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,5.4,Jun 2020,Maruti Suzuki,Eeco,CNG + Cng,Manual,Ahmedabad,34000,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
1,2.95,Dec 2018,Maruti Suzuki,Omni,Petrol,Manual,Ahmedabad,2200,White,First,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",8,minivan
2,3.11,Jun 2014,Maruti Suzuki,Eeco,CNG + Cng,Manual,Ahmedabad,67000,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
3,3.95,Nov 2016,Maruti Suzuki,Eeco,Petrol + Cng,Manual,Ahmedabad,60000,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
4,2.95,Jun 2012,Maruti Suzuki,Eeco,Petrol,Manual,Ahmedabad,22346,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan

In [47]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Ahmedabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [48]:
srch = driver.find_element_by_xpath('//div[@class="cityNameWrap table margin-auto position-rel padding-bottom10 validWidget"]//input')
srch.send_keys('Ahmedabad, Gujarat')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(6)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [49]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[2]/span[1]')
hat.click()
time.sleep(10)
hat1 = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[6]/span[1]')
hat1.click()

In [50]:
for i in range(0,10):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [51]:
cpe_url = []
cpe = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in cpe:
    cpe_url.append(i.get_attribute('href'))
len(cpe_url)

7

In [52]:
cprice = []
cyear = []
cmake = []
cmodel = []
cfuel = []
ctrans = []
clocation = []
cmile = []
ccolor = []
cowner =[]
cengine = []
cseating = []

for link in cpe_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        cprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        cprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        cyear.append(yea.text)
    except NoSuchElementException:
        cyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        cmake.append(mak.text)
    except NoSuchElementException:
        cmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        cfuel.append(fu.text)
    except NoSuchElementException:
        cfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        ctrans.append(tr.text)
    except NoSuchElementException:
        ctrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        clocation.append(loc.text)
    except NoSuchElementException:
        clocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        cmodel.append(mod.text)
    except NoSuchElementException:
        cmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        cmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        cmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        ccolor.append(col.text)
    except NoSuchElementException:
        ccolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        cowner.append(own.text)
    except NoSuchElementException:
        cowner.append('-')
    time.sleep(2)

    try:
        try:
            driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
            time.sleep(2)
            eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
            cengine.append(eng.text)
        except NoSuchElementException:
            cengine.append('-')
    except ElementClickInterceptedException:
        cengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        cseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        cseating.append('-')

In [53]:
cpe_ahm = pd.DataFrame({})
cpe_ahm['price'] = cprice
cpe_ahm['year'] = cyear
cpe_ahm['make'] = cmake
cpe_ahm['model'] = cmodel
cpe_ahm['fuel'] = cfuel
cpe_ahm['trans'] = ctrans
cpe_ahm['location'] = clocation
cpe_ahm['mile'] = cmile
cpe_ahm['color'] = ccolor
cpe_ahm['owner'] = cowner
cpe_ahm['engine'] = cengine
cpe_ahm['seating'] = cseating
cpe_ahm['Body'] = 'coupe/convertible'
cpe_ahm.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,38.5,Jun 2015,Audi,A3,Petrol,Automatic,Ahmedabad,10600,Blue,First,"1798 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",4,coupe/convertible
1,72,May 2016,Jaguar,F-type,Petrol,Automatic,Ahmedabad,8800,Red,Second,"2995 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",2,coupe/convertible
2,1.8,Nov 2006,Tata,Indigo,Petrol,Manual,Ahmedabad,82000,Arctic Silver,Second,"1396 cc, 4 Cylinders Inline, 2 Valves/Cylinder",5,coupe/convertible
3,4,Oct 2014,Volkswagen,1600,Petrol,Manual,Ahmedabad,200000,Black,First,-,-,coupe/convertible
4,45,Dec 2016,Mercedes-Benz,CLS,Diesel,Automatic,Ahmedabad,50000,Blue,Second,"2143 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",4,coupe/convertible

In [54]:
cars_kol = pd.concat([hatch_ahm,suv_ahm,sdn_ahm,van_ahm,cpe_ahm], axis = 0, ignore_index =True)

In [55]:
cars_kol.to_excel('cars_ahm.xlsx', index = False)