In [1]:
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

In [2]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [3]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()

In [4]:
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Jaipur')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [5]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Jaipur, Rajasthan')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [7]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(1)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[1]')
hat.click()

In [8]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,10000)")
    time.sleep(3)
    driver.execute_script("window.scrollBy(0,-6000)")

In [9]:
hatch_url = []
hatch = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in hatch:
    hatch_url.append(i.get_attribute('href'))
len(hatch_url)

246

In [10]:
price = []
year = []
make = []
model = []
fuel = []
trans = []
location = []
mile = []
color = []
owner =[]
engine = []
seating = []

for link in hatch_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        price.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        price.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        year.append(yea.text)
    except NoSuchElementException:
        year.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        make.append(mak.text)
    except NoSuchElementException:
        make.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        fuel.append(fu.text)
    except NoSuchElementException:
        fuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        trans.append(tr.text)
    except NoSuchElementException:
        trans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        model.append(mod.text)
    except NoSuchElementException:
        model.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        mile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        mile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        color.append(col.text)
    except NoSuchElementException:
        color.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        owner.append(own.text)
    except NoSuchElementException:
        owner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        engine.append(eng.text)
    except NoSuchElementException:
        engine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        seating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        seating.append('-')

In [11]:
hatch_jai = pd.DataFrame({})
hatch_jai['price'] = price
hatch_jai['year'] = year
hatch_jai['make'] = make
hatch_jai['model'] = model
hatch_jai['fuel'] = fuel
hatch_jai['trans'] = trans
hatch_jai['location'] = location
hatch_jai['mile'] = mile
hatch_jai['color'] = color
hatch_jai['owner'] = owner
hatch_jai['engine'] = engine
hatch_jai['seating'] = seating
hatch_jai.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,4.75,Jun 2016,Honda,Brio,Petrol,Automatic,Jaipur,35300,Brown,First,"1198 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
1,1.9,Jun 2008,Hyundai,i10,Petrol,Manual,Jaipur,83500,Grey,First,"1086 cc, 4 Cylinders Inline, 3 Valves/Cylinder",5
2,4.7,May 2018,Tata,Tiago,Diesel,Manual,Jaipur,33500,Brown,Second,"1047 cc, 3 Cylinders Inline, 4 Valves/Cylinder...",5
3,3.95,Jun 2017,Tata,Tiago,Petrol,Manual,Jaipur,64000,Brown,Second,"1047 cc, 3 Cylinders Inline, 4 Valves/Cylinder...",5
4,5.9,May 2016,Hyundai,i20 Active,Petrol,Manual,Jaipur,49674,Brown,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [12]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [13]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Jaipur')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(4)

In [14]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Jaipur, Rajasthan')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [15]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[3]/span[1]')
hat.click()

In [18]:
for i in range(0,300):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    driver.execute_script("window.scrollBy(0,-500)")

In [19]:
suv_url = []
suv = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in suv:
    suv_url.append(i.get_attribute('href'))
len(suv_url)

245

In [20]:
sprice = []
syear = []
smake = []
smodel = []
sfuel = []
strans = []
slocation = []
smile = []
scolor = []
sowner =[]
sengine = []
sseating = []

for link in suv_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        syear.append(yea.text)
    except NoSuchElementException:
        syear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        smake.append(mak.text)
    except NoSuchElementException:
        smake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sfuel.append(fu.text)
    except NoSuchElementException:
        sfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        strans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        slocation.append(loc.text)
    except NoSuchElementException:
        slocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        smodel.append(mod.text)
    except NoSuchElementException:
        smodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        smile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        smile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        scolor.append(col.text)
    except NoSuchElementException:
        scolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sowner.append(own.text)
    except NoSuchElementException:
        sowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sengine.append(eng.text)
    except NoSuchElementException:
        sengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sseating.append('-')

In [21]:
suv_jai = pd.DataFrame({})
suv_jai['price'] = sprice
suv_jai['year'] = syear
suv_jai['make'] = smake
suv_jai['model'] = smodel
suv_jai['fuel'] = sfuel
suv_jai['trans'] = strans
suv_jai['location'] = slocation
suv_jai['mile'] = smile
suv_jai['color'] = scolor
suv_jai['owner'] = sowner
suv_jai['engine'] = sengine
suv_jai['seating'] = sseating
suv_jai.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,19.5,Jun 2019,Mahindra,Scorpio,Diesel,Manual,Jaipur,66800,Black,First,"2179 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7
1,18.9,Jun 2019,Jeep,Compass,Petrol,Automatic,Jaipur,8000,Black,First,"1368 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
2,12.5,Jun 2019,Hyundai,Creta,Diesel,Manual,Jaipur,31121,Silver,First,"1396 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
3,8.25,Sep 2017,Honda,WR-V,Diesel,Manual,Jaipur,48650,White,First,"1498 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
4,5.5,Jun 2014,Renault,Duster,Diesel,Manual,Jaipur,117700,White,First,"1461 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [22]:
hatch_jai['Body'] = 'hatchback'
suv_jai['Body'] = 'SUV'

In [24]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Jaipur')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(10)

In [26]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Jaipur, Rajasthan')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(15)

In [28]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[5]/span[1]')
hat.click()

In [29]:
for i in range(0,1000):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(1)
    driver.execute_script("window.scrollBy(0,-500)")

In [30]:
sdn_url = []
sdn = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in sdn:
    sdn_url.append(i.get_attribute('href'))
len(sdn_url)

247

In [32]:
sdprice = []
sdyear = []
sdmake = []
sdmodel = []
sdfuel = []
sdtrans = []
sdlocation = []
sdmile = []
sdcolor = []
sdowner =[]
sdengine = []
sdseating = []

for link in sdn_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sdprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sdprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        sdyear.append(yea.text)
    except NoSuchElementException:
        sdyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        sdmake.append(mak.text)
    except NoSuchElementException:
        sdmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sdfuel.append(fu.text)
    except NoSuchElementException:
        sdfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        sdtrans.append(tr.text)
    except NoSuchElementException:
        sdtrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        sdlocation.append(loc.text)
    except NoSuchElementException:
        sdlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        sdmodel.append(mod.text)
    except NoSuchElementException:
        sdmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        sdmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        sdmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        sdcolor.append(col.text)
    except NoSuchElementException:
        sdcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sdowner.append(own.text)
    except NoSuchElementException:
        sdowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sdengine.append(eng.text)
    except NoSuchElementException:
        sdengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sdseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sdseating.append('-')

In [33]:
sdn_jai = pd.DataFrame({})
sdn_jai['price'] = sdprice
sdn_jai['year'] = sdyear
sdn_jai['make'] = sdmake
sdn_jai['model'] = sdmodel
sdn_jai['fuel'] = sdfuel
sdn_jai['trans'] = sdtrans
sdn_jai['location'] = sdlocation
sdn_jai['mile'] = sdmile
sdn_jai['color'] = sdcolor
sdn_jai['owner'] = sdowner
sdn_jai['engine'] = sdengine
sdn_jai['seating'] = sdseating
sdn_jai['Body'] = 'sedan'
sdn_jai.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,8,Oct 2018,Volkswagen,Vento,Diesel,Manual,Jaipur,69664,Grey,First,"1498 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
1,11.8,Jun 2018,Hyundai,Verna,Petrol,Manual,Jaipur,57200,White,First,"1591 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
2,6.4,Jun 2019,Honda,Amaze,Petrol,Manual,Jaipur,21000,White,First,"1199 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
3,4.95,May 2017,Ford,Aspire,Petrol,Manual,Jaipur,44892,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
4,20.5,Jun 2013,Audi,A6,Diesel,Automatic,Jaipur,83000,Blue,First,"1968 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan

In [37]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Jaipur')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(20)

In [38]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Jaipur, Rajasthan')
time.sleep(10)
srch.send_keys(Keys.ENTER)
time.sleep(10)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [39]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[4]/span[1]')
hat.click()

In [40]:
for i in range(0,10):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [41]:
van_url = []
van = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in van:
    van_url.append(i.get_attribute('href'))
len(van_url)

19

In [42]:
vprice = []
vyear = []
vmake = []
vmodel = []
vfuel = []
vtrans = []
vlocation = []
vmile = []
vcolor = []
vowner =[]
vengine = []
vseating = []

for link in van_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        vprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        vprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        vyear.append(yea.text)
    except NoSuchElementException:
        vyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        vmake.append(mak.text)
    except NoSuchElementException:
        vmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        vfuel.append(fu.text)
    except NoSuchElementException:
        vfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        vtrans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        vlocation.append(loc.text)
    except NoSuchElementException:
        vlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        vmodel.append(mod.text)
    except NoSuchElementException:
        vmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        vmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        vmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        vcolor.append(col.text)
    except NoSuchElementException:
        vcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        vowner.append(own.text)
    except NoSuchElementException:
        vowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        vengine.append(eng.text)
    except NoSuchElementException:
        vengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        vseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        vseating.append('-')

In [44]:
vtrans = vtrans.append(['Manual','Manual','Manual'])

In [45]:
van_kol = pd.DataFrame({})
van_kol['price'] = vprice
van_kol['year'] = vyear
van_kol['make'] = vmake
van_kol['model'] = vmodel
van_kol['fuel'] = vfuel
van_kol['trans'] = vtrans
van_kol['location'] = vlocation
van_kol['mile'] = vmile
van_kol['color'] = vcolor
van_kol['owner'] = vowner
van_kol['engine'] = vengine
van_kol['seating'] = vseating
van_kol['Body'] = 'minivan'
van_kol.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,2.65,Jun 2016,Maruti Suzuki,Omni,Petrol,None,Jaipur,42200,White,First,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",5,minivan
1,4.45,Jun 2019,Maruti Suzuki,Eeco,Petrol,None,Jaipur,44470,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
2,2.21,Jun 2010,Maruti Suzuki,Eeco,Petrol,None,Jaipur,55000,Blue,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
3,2.4,Jun 2017,Maruti Suzuki,Omni,Petrol,None,Jaipur,68123,White,First,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",5,minivan
4,5,Apr 2016,Tata,Winger,Diesel,None,Jaipur,51000,Gold,First,-,-,minivan

In [46]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Jaipur')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [47]:
srch = driver.find_element_by_xpath('//div[@class="cityNameWrap table margin-auto position-rel padding-bottom10 validWidget"]//input')
srch.send_keys('Kolkata, West Bengal')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(6)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [48]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[2]/span[1]')
hat.click()
time.sleep(10)
hat1 = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[6]/span[1]')
hat1.click()

In [49]:
for i in range(0,100):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [50]:
cpe_url = []
cpe = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in cpe:
    cpe_url.append(i.get_attribute('href'))
len(cpe_url)

10

In [51]:
cprice = []
cyear = []
cmake = []
cmodel = []
cfuel = []
ctrans = []
clocation = []
cmile = []
ccolor = []
cowner =[]
cengine = []
cseating = []

for link in cpe_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        cprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        cprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        cyear.append(yea.text)
    except NoSuchElementException:
        cyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        cmake.append(mak.text)
    except NoSuchElementException:
        cmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        cfuel.append(fu.text)
    except NoSuchElementException:
        cfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        ctrans.append(tr.text)
    except NoSuchElementException:
        ctrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        clocation.append(loc.text)
    except NoSuchElementException:
        clocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        cmodel.append(mod.text)
    except NoSuchElementException:
        cmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        cmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        cmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        ccolor.append(col.text)
    except NoSuchElementException:
        ccolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        cowner.append(own.text)
    except NoSuchElementException:
        cowner.append('-')
    time.sleep(2)

    try:
        try:
            driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
            time.sleep(2)
            eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
            cengine.append(eng.text)
        except NoSuchElementException:
            cengine.append('-')
    except ElementClickInterceptedException:
        cengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        cseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        cseating.append('-')

In [52]:
cpe_jai = pd.DataFrame({})
cpe_jai['price'] = cprice
cpe_jai['year'] = cyear
cpe_jai['make'] = cmake
cpe_jai['model'] = cmodel
cpe_jai['fuel'] = cfuel
cpe_jai['trans'] = ctrans
cpe_jai['location'] = clocation
cpe_jai['mile'] = cmile
cpe_jai['color'] = ccolor
cpe_jai['owner'] = cowner
cpe_jai['engine'] = cengine
cpe_jai['seating'] = cseating
cpe_jai['Body'] = 'coupe/convertible'
cpe_jai.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,55,Jun 2017,Mercedes-Benz,GLC Coupe,Petrol,Automatic,Kolkata,22000,Red,First,"2996 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",4,coupe/convertible
1,39,Nov 2020,BMW,2 Series Gran Coupe,Diesel,Automatic,Kolkata,5000,Grey,UnRegistered Car,233 Kmph,5,coupe/convertible
2,1.4 Crore,Jun 2019,BMW,i8,Petrol,Automatic,Kolkata,1500,Bronze,First,"1499 cc, 3 Cylinders Inline, 4 Valves/Cylinder...",4,coupe/convertible
3,37.5,Jun 2017,Audi,A3,Petrol,Automatic,Kolkata,13000,Blue,First,"1798 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",4,coupe/convertible
4,85,Jun 2019,BMW,Z4,Petrol,Automatic,Kolkata,8500,Black,First,4.5 seconds,2,coupe/convertible

In [54]:
cars_jai = pd.concat([hatch_jai,suv_jai,sdn_jai,van_kol,cpe_jai], axis = 0, ignore_index =True)

In [55]:
cars_jai.to_excel('cars_jai.xlsx', index = False)