In [1]:
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

In [2]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [4]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()

In [5]:
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Hyderabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [6]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Hyderabad, Telangana')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [8]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(1)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[1]')
hat.click()

In [9]:
for i in range(0,750):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [10]:
hatch_url = []
hatch = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in hatch:
    hatch_url.append(i.get_attribute('href'))
len(hatch_url)

248

In [11]:
price = []
year = []
make = []
model = []
fuel = []
trans = []
location = []
mile = []
color = []
owner =[]
engine = []
seating = []

for link in hatch_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        price.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        price.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        year.append(yea.text)
    except NoSuchElementException:
        year.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        make.append(mak.text)
    except NoSuchElementException:
        make.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        fuel.append(fu.text)
    except NoSuchElementException:
        fuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        trans.append(tr.text)
    except NoSuchElementException:
        trans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        model.append(mod.text)
    except NoSuchElementException:
        model.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        mile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        mile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        color.append(col.text)
    except NoSuchElementException:
        color.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        owner.append(own.text)
    except NoSuchElementException:
        owner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        engine.append(eng.text)
    except NoSuchElementException:
        engine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        seating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        seating.append('-')

In [12]:
hatch_hyd = pd.DataFrame({})
hatch_hyd['price'] = price
hatch_hyd['year'] = year
hatch_hyd['make'] = make
hatch_hyd['model'] = model
hatch_hyd['fuel'] = fuel
hatch_hyd['trans'] = trans
hatch_hyd['location'] = location
hatch_hyd['mile'] = mile
hatch_hyd['color'] = color
hatch_hyd['owner'] = owner
hatch_hyd['engine'] = engine
hatch_hyd['seating'] = seating
hatch_hyd.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,3.25,Jun 2016,Maruti Suzuki,Alto,Petrol,Manual,Hyderabad,51000,Grey,First,"998 cc, 3 Cylinders Inline, 4 Valves/Cylinder,...",5
1,47,Jun 2020,MINI,Cooper,Petrol,Automatic,Hyderabad,2500,Green,UnRegistered Car,"1998 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",4
2,6.5,Jun 2018,Hyundai,Grand i10,Petrol,Manual,Hyderabad,36100,Grey,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
3,4.5,Jun 2013,Hyundai,i20,Diesel,Manual,Hyderabad,67874,Bronze,First,"1336 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
4,7.2,Jun 2019,Maruti Suzuki,Baleno,Petrol,Manual,Hyderabad,20882,Blue,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [22]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [14]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Hyderabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(4)

In [15]:
#time.sleep(25)
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Hyderabad, Telangana')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [16]:
time.sleep(10)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[3]/span[1]')
hat.click()

In [17]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(1)
    driver.execute_script("window.scrollBy(0,-500)")

In [19]:
suv_url = []
suv = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in suv:
    suv_url.append(i.get_attribute('href'))
len(suv_url)

246

In [20]:
sprice = []
syear = []
smake = []
smodel = []
sfuel = []
strans = []
slocation = []
smile = []
scolor = []
sowner =[]
sengine = []
sseating = []

for link in suv_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        syear.append(yea.text)
    except NoSuchElementException:
        syear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        smake.append(mak.text)
    except NoSuchElementException:
        smake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sfuel.append(fu.text)
    except NoSuchElementException:
        sfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        strans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        slocation.append(loc.text)
    except NoSuchElementException:
        slocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        smodel.append(mod.text)
    except NoSuchElementException:
        smodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        smile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        smile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        scolor.append(col.text)
    except NoSuchElementException:
        scolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sowner.append(own.text)
    except NoSuchElementException:
        sowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sengine.append(eng.text)
    except NoSuchElementException:
        sengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sseating.append('-')

In [21]:
suv_hyd = pd.DataFrame({})
suv_hyd['price'] = sprice
suv_hyd['year'] = syear
suv_hyd['make'] = smake
suv_hyd['model'] = smodel
suv_hyd['fuel'] = sfuel
suv_hyd['trans'] = strans
suv_hyd['location'] = slocation
suv_hyd['mile'] = smile
suv_hyd['color'] = scolor
suv_hyd['owner'] = sowner
suv_hyd['engine'] = sengine
suv_hyd['seating'] = sseating
suv_hyd.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,29,Jun 2012,Porsche,Cayenne,Diesel,Automatic,Hyderabad,135256,Blue,First,"2967 cc, 6 Cylinders Flat, 4 Valves/Cylinder, ...",5
1,52,Jun 2018,Audi,Q5,Petrol,Automatic,Hyderabad,44700,White,First,Petrol,-
2,5.6,Jun 2006,Toyota,Innova,Diesel,Manual,Hyderabad,190417,Silver,First,"2494 cc, 4 Cylinders 4 Valves/Cylinder",7
3,20,Jun 2020,MG,Hector,Petrol,Automatic,Hyderabad,18967,Black,First,"1451 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
4,11.6,Jun 2016,Hyundai,Creta,Diesel,Manual,Hyderabad,56785,Grey,First,"1582 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [23]:
hatch_hyd['Body'] = 'hatchback'
suv_hyd['Body'] = 'SUV'

In [24]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Hyderabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(10)

In [25]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Hyderabad, Telangana')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(15)

In [28]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[7]')
hat.click()

In [29]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [30]:
sdn_url = []
sdn = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in sdn:
    sdn_url.append(i.get_attribute('href'))
len(sdn_url)

248

In [31]:
sdprice = []
sdyear = []
sdmake = []
sdmodel = []
sdfuel = []
sdtrans = []
sdlocation = []
sdmile = []
sdcolor = []
sdowner =[]
sdengine = []
sdseating = []

for link in sdn_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sdprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sdprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        sdyear.append(yea.text)
    except NoSuchElementException:
        sdyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        sdmake.append(mak.text)
    except NoSuchElementException:
        sdmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sdfuel.append(fu.text)
    except NoSuchElementException:
        sdfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        sdtrans.append(tr.text)
    except NoSuchElementException:
        sdtrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        sdlocation.append(loc.text)
    except NoSuchElementException:
        sdlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        sdmodel.append(mod.text)
    except NoSuchElementException:
        sdmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        sdmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        sdmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        sdcolor.append(col.text)
    except NoSuchElementException:
        sdcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sdowner.append(own.text)
    except NoSuchElementException:
        sdowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sdengine.append(eng.text)
    except NoSuchElementException:
        sdengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sdseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sdseating.append('-')

In [32]:
sdn_hyd = pd.DataFrame({})
sdn_hyd['price'] = sdprice
sdn_hyd['year'] = sdyear
sdn_hyd['make'] = sdmake
sdn_hyd['model'] = sdmodel
sdn_hyd['fuel'] = sdfuel
sdn_hyd['trans'] = sdtrans
sdn_hyd['location'] = sdlocation
sdn_hyd['mile'] = sdmile
sdn_hyd['color'] = sdcolor
sdn_hyd['owner'] = sdowner
sdn_hyd['engine'] = sdengine
sdn_hyd['seating'] = sdseating
sdn_hyd['Body'] = 'sedan'
sdn_hyd.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,3.9,Jun 2010,Honda,City,Petrol,Manual,Hyderabad,78394,White,First,"1497 cc, 4 Cylinders Inline, 4 Valves/Cylinder",5,sedan
1,4.3,Jun 2011,Volkswagen,Vento,Diesel,Manual,Hyderabad,95687,White,First,"1598 cc, 4 Cylinders Inline, 4 Valves/Cylinder",5,sedan
2,5,Jun 2011,Skoda,Laura,Diesel,Automatic,Hyderabad,78000,White,First,"1968 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
3,55,Jun 2014,Audi,A8,Diesel,Automatic,Hyderabad,45000,White,First,"2967 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",4,sedan
4,4.25,Jun 2010,Honda,Civic,Petrol,Manual,Hyderabad,59396,Grey,First,"1799 cc, 4 Cylinders Inline, 4 Valves/Cylinder",5,sedan

In [33]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Hyderabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(20)

In [34]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Hyderabad, Telangana')
time.sleep(10)
srch.send_keys(Keys.ENTER)
time.sleep(10)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [35]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[4]/span[1]')
hat.click()

In [37]:
for i in range(0,20):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [38]:
van_url = []
van = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in van:
    van_url.append(i.get_attribute('href'))
len(van_url)

27

In [39]:
vprice = []
vyear = []
vmake = []
vmodel = []
vfuel = []
vtrans = []
vlocation = []
vmile = []
vcolor = []
vowner =[]
vengine = []
vseating = []

for link in van_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        vprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        vprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        vyear.append(yea.text)
    except NoSuchElementException:
        vyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        vmake.append(mak.text)
    except NoSuchElementException:
        vmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        vfuel.append(fu.text)
    except NoSuchElementException:
        vfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        vtrans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        vlocation.append(loc.text)
    except NoSuchElementException:
        vlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        vmodel.append(mod.text)
    except NoSuchElementException:
        vmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        vmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        vmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        vcolor.append(col.text)
    except NoSuchElementException:
        vcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        vowner.append(own.text)
    except NoSuchElementException:
        vowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        vengine.append(eng.text)
    except NoSuchElementException:
        vengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        vseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        vseating.append('-')

In [64]:
#vtrans = vtrans.append('Manual')

In [40]:
van_kol = pd.DataFrame({})
van_kol['price'] = vprice
van_kol['year'] = vyear
van_kol['make'] = vmake
van_kol['model'] = vmodel
van_kol['fuel'] = vfuel
van_kol['trans'] = vtrans
van_kol['location'] = vlocation
van_kol['mile'] = vmile
van_kol['color'] = vcolor
van_kol['owner'] = vowner
van_kol['engine'] = vengine
van_kol['seating'] = vseating
van_kol['Body'] = 'minivan'
van_kol.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,3.35,Jun 2017,Maruti Suzuki,Omni,Petrol,Manual,Hyderabad,26085,Silver,First,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",8,minivan
1,4.15,Dec 2017,Maruti Suzuki,Eeco,Petrol,Manual,Hyderabad,24425,White,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
2,2.9,Jun 2011,Maruti Suzuki,Eeco,Petrol,Manual,Hyderabad,63100,Grey,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7,minivan
3,4.32,Jun 2018,Maruti Suzuki,Eeco,Petrol + Lpg,Manual,Hyderabad,39303,Grey,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7,minivan
4,2.9,Jun 2016,Maruti Suzuki,Omni,Petrol,Manual,Hyderabad,22994,White,First,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",8,minivan

In [42]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Hyderabad')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [ ]:
srch = driver.find_element_by_xpath('//div[@class="cityNameWrap table margin-auto position-rel padding-bottom10 validWidget"]//input')
srch.send_keys('Hyderabad, Telangana')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(6)

In [44]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [45]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[2]/span[1]')
hat.click()
time.sleep(10)
hat1 = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[8]/span[1]')
hat1.click()

In [47]:
for i in range(0,10):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    driver.execute_script("window.scrollBy(0,-500)")

In [48]:
cpe_url = []
cpe = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in cpe:
    cpe_url.append(i.get_attribute('href'))
len(cpe_url)

19

In [49]:
cprice = []
cyear = []
cmake = []
cmodel = []
cfuel = []
ctrans = []
clocation = []
cmile = []
ccolor = []
cowner =[]
cengine = []
cseating = []

for link in cpe_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        cprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        cprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        cyear.append(yea.text)
    except NoSuchElementException:
        cyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        cmake.append(mak.text)
    except NoSuchElementException:
        cmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        cfuel.append(fu.text)
    except NoSuchElementException:
        cfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        ctrans.append(tr.text)
    except NoSuchElementException:
        ctrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        clocation.append(loc.text)
    except NoSuchElementException:
        clocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        cmodel.append(mod.text)
    except NoSuchElementException:
        cmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        cmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        cmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        ccolor.append(col.text)
    except NoSuchElementException:
        ccolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        cowner.append(own.text)
    except NoSuchElementException:
        cowner.append('-')
    time.sleep(2)

    try:
        try:
            driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
            time.sleep(2)
            eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
            cengine.append(eng.text)
        except NoSuchElementException:
            cengine.append('-')
    except ElementClickInterceptedException:
        cengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        cseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        cseating.append('-')

In [50]:
cpe_hyd = pd.DataFrame({})
cpe_hyd['price'] = cprice
cpe_hyd['year'] = cyear
cpe_hyd['make'] = cmake
cpe_hyd['model'] = cmodel
cpe_hyd['fuel'] = cfuel
cpe_hyd['trans'] = ctrans
cpe_hyd['location'] = clocation
cpe_hyd['mile'] = cmile
cpe_hyd['color'] = ccolor
cpe_hyd['owner'] = cowner
cpe_hyd['engine'] = cengine
cpe_hyd['seating'] = cseating
cpe_hyd['Body'] = 'coupe/convertible'
cpe_hyd.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,9,Jun 2012,Volvo,S60,Diesel,Automatic,Hyderabad,85000,Red,First,"1984 cc, 5 Cylinders Inline, 4 Valves/Cylinder...",5,coupe/convertible
1,57,Jun 2019,Audi,TT,Petrol,Automatic,Hyderabad,4000,White,First,"1984 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",2,coupe/convertible
2,75,Jun 2017,Ford,Mustang,Petrol,Automatic,Hyderabad,10000,Black,First,"4951 cc, 8 Cylinders In V Shape, 4 Valves/Cyli...",4,coupe/convertible
3,10.8,Jun 2012,Volvo,S60,Diesel,Automatic,Hyderabad,138000,Silver,First,"1984 cc, 5 Cylinders Inline, 4 Valves/Cylinder...",5,coupe/convertible
4,49,Jun 2015,Mercedes-Benz,CLS,Diesel,Automatic,Hyderabad,11000,Blue,First,"2143 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",4,coupe/convertible

In [52]:
cars_hyd = pd.concat([hatch_hyd,suv_hyd,sdn_hyd,van_kol,cpe_hyd], axis = 0, ignore_index =True)

In [53]:
cars_hyd.to_excel('cars_hyd.xlsx', index = False)