In [1]:
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

In [2]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [3]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()

In [4]:
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Coimbatore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [5]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Coimbatore, Tamil Nadu')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [6]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(1)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[1]')
hat.click()

In [7]:
for i in range(0,100):
    driver.execute_script("window.scrollBy(0,10000)")
    time.sleep(1)
    driver.execute_script("window.scrollBy(0,-6000)")

In [8]:
hatch_url = []
hatch = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in hatch:
    hatch_url.append(i.get_attribute('href'))
len(hatch_url)

247

In [9]:
price = []
year = []
make = []
model = []
fuel = []
trans = []
location = []
mile = []
color = []
owner =[]
engine = []
seating = []

for link in hatch_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        price.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        price.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        year.append(yea.text)
    except NoSuchElementException:
        year.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        make.append(mak.text)
    except NoSuchElementException:
        make.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        fuel.append(fu.text)
    except NoSuchElementException:
        fuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        trans.append(tr.text)
    except NoSuchElementException:
        trans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        model.append(mod.text)
    except NoSuchElementException:
        model.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        mile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        mile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        color.append(col.text)
    except NoSuchElementException:
        color.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        owner.append(own.text)
    except NoSuchElementException:
        owner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        engine.append(eng.text)
    except NoSuchElementException:
        engine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        seating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        seating.append('-')

In [10]:
hatch_co = pd.DataFrame({})
hatch_co['price'] = price
hatch_co['year'] = year
hatch_co['make'] = make
hatch_co['model'] = model
hatch_co['fuel'] = fuel
hatch_co['trans'] = trans
hatch_co['location'] = location
hatch_co['mile'] = mile
hatch_co['color'] = color
hatch_co['owner'] = owner
hatch_co['engine'] = engine
hatch_co['seating'] = seating
hatch_co.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,5.9,Sep 2015,Honda,Jazz,Diesel,Manual,Coimbatore,79730,White,First,"1498 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
1,2.75,Aug 2011,Maruti Suzuki,Alto,Petrol,Manual,Coimbatore,33500,Maroon,Second,"998 cc, 3 Cylinders Inline, 4 Valves/Cylinder,...",5
2,2.65,Oct 2016,Datsun,Redigo,Petrol,Manual,Coimbatore,41740,Green,Second,"799 cc, 3 Cylinders Inline, 4 Valves/Cylinder,...",5
3,5.5,Mar 2015,Hyundai,Elite i20,Diesel,Manual,Coimbatore,82000,Grey,Second,"1396 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
4,8,Jun 2018,Volkswagen,Polo,Petrol,Automatic,Coimbatore,80000,Red,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [11]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [12]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Coimbatore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(4)

In [13]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Coimbatore, Tamil Nadu')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [14]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[3]/span[1]')
hat.click()

In [18]:
for i in range(0,1):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(1)
    driver.execute_script("window.scrollBy(0,-500)")

In [19]:
suv_url = []
suv = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in suv:
    suv_url.append(i.get_attribute('href'))
len(suv_url)

223

In [20]:
sprice = []
syear = []
smake = []
smodel = []
sfuel = []
strans = []
slocation = []
smile = []
scolor = []
sowner =[]
sengine = []
sseating = []

for link in suv_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        syear.append(yea.text)
    except NoSuchElementException:
        syear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        smake.append(mak.text)
    except NoSuchElementException:
        smake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sfuel.append(fu.text)
    except NoSuchElementException:
        sfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        strans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        slocation.append(loc.text)
    except NoSuchElementException:
        slocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        smodel.append(mod.text)
    except NoSuchElementException:
        smodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        smile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        smile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        scolor.append(col.text)
    except NoSuchElementException:
        scolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sowner.append(own.text)
    except NoSuchElementException:
        sowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sengine.append(eng.text)
    except NoSuchElementException:
        sengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sseating.append('-')

In [21]:
suv_co = pd.DataFrame({})
suv_co['price'] = sprice
suv_co['year'] = syear
suv_co['make'] = smake
suv_co['model'] = smodel
suv_co['fuel'] = sfuel
suv_co['trans'] = strans
suv_co['location'] = slocation
suv_co['mile'] = smile
suv_co['color'] = scolor
suv_co['owner'] = sowner
suv_co['engine'] = sengine
suv_co['seating'] = sseating
suv_co.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,19.9,Dec 2015,Toyota,Fortuner,Diesel,Automatic,Coimbatore,55530,Silver,Second,"2982 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7
1,63.5,May 2019,Audi,Q5,Diesel,Automatic,Coimbatore,24500,White,First,"1968 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
2,31,Jun 2017,Audi,Q3,Diesel,Automatic,Coimbatore,30000,White,First,"1968 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
3,18,Jun 2014,Audi,Q3,Diesel,Automatic,Coimbatore,55400,Black,Second,"1968 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
4,9.1,Mar 2014,Mahindra,XUV500,Diesel,Manual,Coimbatore,64000,White,First,"2179 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7

In [22]:
hatch_co['Body'] = 'hatchback'
suv_co['Body'] = 'SUV'

In [24]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Coimbatore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(10)

In [25]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Kolkata, West Bengal')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(15)

In [26]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[5]/span[1]')
hat.click()

In [29]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(3)
    driver.execute_script("window.scrollBy(0,-500)")

In [30]:
sdn_url = []
sdn = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in sdn:
    sdn_url.append(i.get_attribute('href'))
len(sdn_url)

244

In [31]:
sdprice = []
sdyear = []
sdmake = []
sdmodel = []
sdfuel = []
sdtrans = []
sdlocation = []
sdmile = []
sdcolor = []
sdowner =[]
sdengine = []
sdseating = []

for link in sdn_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sdprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sdprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        sdyear.append(yea.text)
    except NoSuchElementException:
        sdyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        sdmake.append(mak.text)
    except NoSuchElementException:
        sdmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sdfuel.append(fu.text)
    except NoSuchElementException:
        sdfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        sdtrans.append(tr.text)
    except NoSuchElementException:
        sdtrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        sdlocation.append(loc.text)
    except NoSuchElementException:
        sdlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        sdmodel.append(mod.text)
    except NoSuchElementException:
        sdmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        sdmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        sdmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        sdcolor.append(col.text)
    except NoSuchElementException:
        sdcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sdowner.append(own.text)
    except NoSuchElementException:
        sdowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sdengine.append(eng.text)
    except NoSuchElementException:
        sdengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sdseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sdseating.append('-')

In [32]:
sdn_co = pd.DataFrame({})
sdn_co['price'] = sdprice
sdn_co['year'] = sdyear
sdn_co['make'] = sdmake
sdn_co['model'] = sdmodel
sdn_co['fuel'] = sdfuel
sdn_co['trans'] = sdtrans
sdn_co['location'] = sdlocation
sdn_co['mile'] = sdmile
sdn_co['color'] = sdcolor
sdn_co['owner'] = sdowner
sdn_co['engine'] = sdengine
sdn_co['seating'] = sdseating
sdn_co['Body'] = 'sedan'
sdn_co.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,4.7,Jun 2017,Hyundai,Xcent,Petrol,Manual,Kolkata,41260,Grey,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
1,3.99,Apr 2016,Honda,Amaze,Petrol,Manual,Kolkata,33000,Brown,First,"1198 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
2,4.59,Jun 2018,Ford,Aspire,Petrol,Manual,Kolkata,40224,Blue,First,"1194 cc, 3 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
3,1.75 Crore,Jun 2018,Porsche,Panamera,Petrol,Automatic,Kolkata,8500,Black,First,"3996 cc, 8 Cylinders In V Shape, 4 Valves/Cyli...",4,sedan
4,18.5,Jun 2013,Jaguar,XF,Diesel,Automatic,Kolkata,6000,Purple,First,"2179 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan

In [34]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Coimbatore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(20)

In [35]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Coimbatore, Tamil Nadu')
time.sleep(10)
srch.send_keys(Keys.ENTER)
time.sleep(10)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [36]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[4]/span[1]')
hat.click()

In [37]:
for i in range(0,20):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [38]:
van_url = []
van = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in van:
    van_url.append(i.get_attribute('href'))
len(van_url)

13

In [39]:
vprice = []
vyear = []
vmake = []
vmodel = []
vfuel = []
vtrans = []
vlocation = []
vmile = []
vcolor = []
vowner =[]
vengine = []
vseating = []

for link in van_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        vprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        vprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        vyear.append(yea.text)
    except NoSuchElementException:
        vyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        vmake.append(mak.text)
    except NoSuchElementException:
        vmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        vfuel.append(fu.text)
    except NoSuchElementException:
        vfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        vtrans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        vlocation.append(loc.text)
    except NoSuchElementException:
        vlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        vmodel.append(mod.text)
    except NoSuchElementException:
        vmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        vmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        vmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        vcolor.append(col.text)
    except NoSuchElementException:
        vcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        vowner.append(own.text)
    except NoSuchElementException:
        vowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        vengine.append(eng.text)
    except NoSuchElementException:
        vengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        vseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        vseating.append('-')

In [64]:
#vtrans = vtrans.append('Manual')

In [40]:
van_co = pd.DataFrame({})
van_co['price'] = vprice
van_co['year'] = vyear
van_co['make'] = vmake
van_co['model'] = vmodel
van_co['fuel'] = vfuel
van_co['trans'] = vtrans
van_co['location'] = vlocation
van_co['mile'] = vmile
van_co['color'] = vcolor
van_co['owner'] = vowner
van_co['engine'] = vengine
van_co['seating'] = vseating
van_co['Body'] = 'minivan'
van_co.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,3.5,Apr 2016,Maruti Suzuki,Eeco,Petrol,Manual,Chennai,12673,Blue,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
1,3.9,Mar 2017,Maruti Suzuki,Eeco,Petrol,Manual,Chennai,33610,Silver,Second,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
2,18.95,Jun 1996,Mercedes-Benz,MB-Class,Diesel,Manual,Dehradun,60000,Silver,Second,-,-,minivan
3,3.49,Jun 1995,Mercedes-Benz,MB-Class,Diesel,Manual,Dehradun,86000,White,Second,-,-,minivan
4,3.5,Nov 2017,Maruti Suzuki,Eeco,Petrol + Petrol,Manual,Coimbatore,132000,Gray,Second,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan

In [42]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Coimbatore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [43]:
srch = driver.find_element_by_xpath('//div[@class="cityNameWrap table margin-auto position-rel padding-bottom10 validWidget"]//input')
srch.send_keys('Coimbatore, Tamil Nadu')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(6)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [44]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[2]/span[1]')
hat.click()
time.sleep(10)
hat1 = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[6]/span[1]')
hat1.click()

In [45]:
for i in range(0,1000):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(3)
    driver.execute_script("window.scrollBy(0,-500)")

In [46]:
cpe_url = []
cpe = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in cpe:
    cpe_url.append(i.get_attribute('href'))
len(cpe_url)

7

In [47]:
cprice = []
cyear = []
cmake = []
cmodel = []
cfuel = []
ctrans = []
clocation = []
cmile = []
ccolor = []
cowner =[]
cengine = []
cseating = []

for link in cpe_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        cprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        cprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        cyear.append(yea.text)
    except NoSuchElementException:
        cyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        cmake.append(mak.text)
    except NoSuchElementException:
        cmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        cfuel.append(fu.text)
    except NoSuchElementException:
        cfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        ctrans.append(tr.text)
    except NoSuchElementException:
        ctrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        clocation.append(loc.text)
    except NoSuchElementException:
        clocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        cmodel.append(mod.text)
    except NoSuchElementException:
        cmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        cmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        cmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        ccolor.append(col.text)
    except NoSuchElementException:
        ccolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        cowner.append(own.text)
    except NoSuchElementException:
        cowner.append('-')
    time.sleep(2)

    try:
        try:
            driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
            time.sleep(2)
            eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
            cengine.append(eng.text)
        except NoSuchElementException:
            cengine.append('-')
    except ElementClickInterceptedException:
        cengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        cseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        cseating.append('-')

In [48]:
cpe_co = pd.DataFrame({})
cpe_co['price'] = cprice
cpe_co['year'] = cyear
cpe_co['make'] = cmake
cpe_co['model'] = cmodel
cpe_co['fuel'] = cfuel
cpe_co['trans'] = ctrans
cpe_co['location'] = clocation
cpe_co['mile'] = cmile
cpe_co['color'] = ccolor
cpe_co['owner'] = cowner
cpe_co['engine'] = cengine
cpe_co['seating'] = cseating
cpe_co['Body'] = 'coupe/convertible'
cpe_co.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,64.9,Jun 2008,Porsche,911,Petrol,Automatic,Chennai,26000,White,Third,"3800 cc, 6 Cylinders Flat, 4 Valves/Cylinder, ...",4,coupe/convertible
1,33.9,Jun 2013,BMW,6-Series,Diesel,Automatic,Chennai,57000,Blue,First,"2993 cc, 6 Cylinders Inline, 4 Valves/Cylinder",5,coupe/convertible
2,69.9,Jun 2014,Jaguar,F-type,Petrol,Automatic,Chennai,10000,Red,First,"2995 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",2,coupe/convertible
3,7.55,Jun 1994,BMW,5-Series,Diesel,Automatic,Dehradun,90000,Blue,First,-,-,coupe/convertible
4,6.99,Jun 1998,BMW,5-Series,Diesel,Automatic,Dehradun,60000,Brown,Second,-,-,coupe/convertible

In [49]:
cars_co = pd.concat([hatch_co,suv_co,sdn_co,van_co,cpe_co], axis = 0, ignore_index =True)

In [50]:
cars_co.to_excel('cars_co.xlsx', index = False)