In [1]:
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

In [2]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [3]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()

In [4]:
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Bangalore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [7]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Bangalore, Karnataka')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [9]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(1)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[1]')
hat.click()

In [13]:
for i in range(0,750):
    driver.execute_script("window.scrollBy(0,10000)")
    driver.execute_script("window.scrollBy(0,-1000)")

In [14]:
hatch_url = []
hatch = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in hatch:
    hatch_url.append(i.get_attribute('href'))
len(hatch_url)

246

In [15]:
price = []
year = []
make = []
model = []
fuel = []
trans = []
location = []
mile = []
color = []
owner =[]
engine = []
seating = []

for link in hatch_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        price.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        price.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        year.append(yea.text)
    except NoSuchElementException:
        year.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        make.append(mak.text)
    except NoSuchElementException:
        make.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        fuel.append(fu.text)
    except NoSuchElementException:
        fuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        trans.append(tr.text)
    except NoSuchElementException:
        trans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        model.append(mod.text)
    except NoSuchElementException:
        model.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        mile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        mile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        color.append(col.text)
    except NoSuchElementException:
        color.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        owner.append(own.text)
    except NoSuchElementException:
        owner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        engine.append(eng.text)
    except NoSuchElementException:
        engine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        seating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        seating.append('-')

In [16]:
hatch_bng = pd.DataFrame({})
hatch_bng['price'] = price
hatch_bng['year'] = year
hatch_bng['make'] = make
hatch_bng['model'] = model
hatch_bng['fuel'] = fuel
hatch_bng['trans'] = trans
hatch_bng['location'] = location
hatch_bng['mile'] = mile
hatch_bng['color'] = color
hatch_bng['owner'] = owner
hatch_bng['engine'] = engine
hatch_bng['seating'] = seating
hatch_bng.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,4.89,Jun 2015,Honda,Brio,Petrol,Manual,Bangalore,21886,Silver,First,"1198 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
1,5.25,Jun 2015,Hyundai,Grand i10,Petrol,Manual,Bangalore,45000,Grey,Second,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
2,6.25,Jun 2016,Hyundai,Grand i10,Petrol,Automatic,Bangalore,37378,Gold,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
3,3.25,Jun 2011,Ford,Figo,Petrol,Manual,Bangalore,88574,Black,First,"1196 cc, 4 Valves/Cylinder",5
4,4.5,Jun 2016,Maruti Suzuki,Wagon R,Petrol,Manual,Bangalore,40000,White,First,"998 cc, 3 Cylinders Inline, 4 Valves/Cylinder,...",5

In [17]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)

In [18]:
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Bangalore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(4)

In [22]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Bangalore, Karnataka')
time.sleep(1)
srch.send_keys(Keys.ENTER)

In [26]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[3]/span[1]')
hat.click()

In [27]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [28]:
suv_url = []
suv = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in suv:
    suv_url.append(i.get_attribute('href'))
len(suv_url)

245

In [29]:
sprice = []
syear = []
smake = []
smodel = []
sfuel = []
strans = []
slocation = []
smile = []
scolor = []
sowner =[]
sengine = []
sseating = []

for link in suv_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        syear.append(yea.text)
    except NoSuchElementException:
        syear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        smake.append(mak.text)
    except NoSuchElementException:
        smake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sfuel.append(fu.text)
    except NoSuchElementException:
        sfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        strans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        slocation.append(loc.text)
    except NoSuchElementException:
        slocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        smodel.append(mod.text)
    except NoSuchElementException:
        smodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        smile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        smile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        scolor.append(col.text)
    except NoSuchElementException:
        scolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sowner.append(own.text)
    except NoSuchElementException:
        sowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sengine.append(eng.text)
    except NoSuchElementException:
        sengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sseating.append('-')

In [30]:
suv_bng = pd.DataFrame({})
suv_bng['price'] = sprice
suv_bng['year'] = syear
suv_bng['make'] = smake
suv_bng['model'] = smodel
suv_bng['fuel'] = sfuel
suv_bng['trans'] = strans
suv_bng['location'] = slocation
suv_bng['mile'] = smile
suv_bng['color'] = scolor
suv_bng['owner'] = sowner
suv_bng['engine'] = sengine
suv_bng['seating'] = sseating
suv_bng.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating
0,11.85,Mar 2017,Hyundai,Creta,Diesel,Manual,Bangalore,68731,White,First,"1582 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
1,13.45,Jun 2017,Hyundai,Creta,Diesel,Manual,Bangalore,60559,White,First,"1582 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5
2,9.1,Jun 2016,Maruti Suzuki,Ertiga,Diesel,Manual,Bangalore,42231,Grey,First,"1248 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",7
3,12.45,Aug 2013,Toyota,Innova,Diesel,Manual,Bangalore,63138,Gold,First,"2494 cc, 4 Cylinders 4 Valves/Cylinder",7
4,6.75,Aug 2013,Ford,Ecosport,Petrol,Automatic,Bangalore,64100,White,First,"1499 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5

In [31]:
hatch_bng['Body'] = 'hatchback'
suv_bng['Body'] = 'SUV'

In [32]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Bangalore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(10)

In [33]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Bangalore, Karnataka')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(15)

In [37]:
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[6]/span[1]')
hat.click()

In [38]:
for i in range(0,500):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [39]:
sdn_url = []
sdn = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in sdn:
    sdn_url.append(i.get_attribute('href'))
len(sdn_url)

246

In [40]:
sdprice = []
sdyear = []
sdmake = []
sdmodel = []
sdfuel = []
sdtrans = []
sdlocation = []
sdmile = []
sdcolor = []
sdowner =[]
sdengine = []
sdseating = []

for link in sdn_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        sdprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        sdprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        sdyear.append(yea.text)
    except NoSuchElementException:
        sdyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        sdmake.append(mak.text)
    except NoSuchElementException:
        sdmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        sdfuel.append(fu.text)
    except NoSuchElementException:
        sdfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        sdtrans.append(tr.text)
    except NoSuchElementException:
        sdtrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        sdlocation.append(loc.text)
    except NoSuchElementException:
        sdlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        sdmodel.append(mod.text)
    except NoSuchElementException:
        sdmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        sdmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        sdmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        sdcolor.append(col.text)
    except NoSuchElementException:
        sdcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        sdowner.append(own.text)
    except NoSuchElementException:
        sdowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        sdengine.append(eng.text)
    except NoSuchElementException:
        sdengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        sdseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        sdseating.append('-')

In [41]:
sdn_bng = pd.DataFrame({})
sdn_bng['price'] = sdprice
sdn_bng['year'] = sdyear
sdn_bng['make'] = sdmake
sdn_bng['model'] = sdmodel
sdn_bng['fuel'] = sdfuel
sdn_bng['trans'] = sdtrans
sdn_bng['location'] = sdlocation
sdn_bng['mile'] = sdmile
sdn_bng['color'] = sdcolor
sdn_bng['owner'] = sdowner
sdn_bng['engine'] = sdengine
sdn_bng['seating'] = sdseating
sdn_bng['Body'] = 'sedan'
sdn_bng.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,9.45,Jun 2018,Volkswagen,Vento,Diesel,Manual,Bangalore,42796,White,First,"1498 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
1,3.25,Jun 2007,Honda,City,Petrol,Manual,Bangalore,76890,Maroon,Second,"1497 cc, 4 Cylinders Inline, 4 Valves/Cylinder",5,sedan
2,2.55,Oct 2006,Honda,City,Petrol,Manual,Bangalore,69357,White,First,"1497 cc, 4 Cylinders Inline, 2 Valves/Cylinder",5,sedan
3,5.75,Jun 2015,Hyundai,Xcent,Petrol,Manual,Bangalore,71000,Silver,First,"1197 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan
4,7.49,Mar 2019,Honda,Amaze,Petrol,Manual,Bangalore,23118,White,First,"1199 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,sedan

In [42]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Kolkata')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()
time.sleep(20)

In [43]:
srch = driver.find_element_by_xpath('//input[@class="cityName ui-autocomplete-input blur inputBlur"]')
srch.send_keys('Bangalore, Karnataka')
time.sleep(10)
srch.send_keys(Keys.ENTER)
time.sleep(10)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [44]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[4]/span[1]')
hat.click()

In [45]:
for i in range(0,50):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [46]:
van_url = []
van = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in van:
    van_url.append(i.get_attribute('href'))
len(van_url)

29

In [47]:
vprice = []
vyear = []
vmake = []
vmodel = []
vfuel = []
vtrans = []
vlocation = []
vmile = []
vcolor = []
vowner =[]
vengine = []
vseating = []

for link in van_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        vprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        vprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        vyear.append(yea.text)
    except NoSuchElementException:
        vyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        vmake.append(mak.text)
    except NoSuchElementException:
        vmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        vfuel.append(fu.text)
    except NoSuchElementException:
        vfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        vtrans.append(tr.text)
    except NoSuchElementException:
        strans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        vlocation.append(loc.text)
    except NoSuchElementException:
        vlocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        vmodel.append(mod.text)
    except NoSuchElementException:
        vmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        vmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        vmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        vcolor.append(col.text)
    except NoSuchElementException:
        vcolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        vowner.append(own.text)
    except NoSuchElementException:
        vowner.append('-')
    time.sleep(2)

    try:
        driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
        time.sleep(2)
        eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
        vengine.append(eng.text)
    except NoSuchElementException:
        vengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        vseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        vseating.append('-')

In [49]:
vtrans = vtrans.extend(['Manual','Manual'])

In [50]:
van_bng = pd.DataFrame({})
van_bng['price'] = vprice
van_bng['year'] = vyear
van_bng['make'] = vmake
van_bng['model'] = vmodel
van_bng['fuel'] = vfuel
van_bng['trans'] = vtrans
van_bng['location'] = vlocation
van_bng['mile'] = vmile
van_bng['color'] = vcolor
van_bng['owner'] = vowner
van_bng['engine'] = vengine
van_bng['seating'] = vseating
van_bng['Body'] = 'minivan'
van_bng.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,3,Jun 2017,Maruti Suzuki,Omni,Petrol,None,Bangalore,60000,Blue,Second,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",5,minivan
1,4.45,Jun 2018,Maruti Suzuki,Eeco,Petrol,None,Bangalore,29127,Silver,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
2,4.45,Jun 2018,Maruti Suzuki,Eeco,Petrol,None,Bangalore,29127,Grey,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
3,4.4,Jun 2018,Maruti Suzuki,Eeco,Petrol,None,Bangalore,17000,Silver,First,"1196 cc, 4 Cylinders Inline, 4 Valves/Cylinder...",5,minivan
4,2.99,Jun 2017,Maruti Suzuki,Omni,Petrol,None,Bangalore,31420,White,First,"796 cc, 3 Cylinders Inline, 2 Valves/Cylinder,...",8,minivan

In [57]:
driver = webdriver.Chrome("chromedriver.exe")
time.sleep(3)
url = 'https://www.carwale.com/'
driver.get(url)
time.sleep(5)
clk = driver.find_element_by_xpath('//div[@class="o-bfyaNx o-dJmcbh o-eCFISO o-djSZRV o-fEEqXL o-bXKmQE"]')
clk.click()
time.sleep(2)
key1 = driver.find_element_by_xpath('//input[@class="o-dqBOwT o-cKuOoN o-eZCpVk o-bfyaNx o-eZTujG o-jjpuv o-fzptVd o-fzptYr o-fEEqXL o-eKWNKE o-bIMsfE o-ItVGT  o-fznJFI E6NC89 _2XUNC9 _2aq9yP  E6NC89 "]')
key1.send_keys('Bangalore')
time.sleep(1)
clk1 = driver.find_element_by_xpath('//div[@class="o-lIIwF"]')
clk1.click()

In [58]:
srch = driver.find_element_by_xpath('//div[@class="cityNameWrap table margin-auto position-rel padding-bottom10 validWidget"]//input')
srch.send_keys('Bangalore, Karnataka')
time.sleep(1)
srch.send_keys(Keys.ENTER)
time.sleep(6)
bod = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/h3')
bod.click()
time.sleep(3)

In [59]:
hat = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[2]/span[1]')
hat.click()
time.sleep(10)
hat1 = driver.find_element_by_xpath('/html/body/div[12]/form/section[2]/div[1]/div[3]/div/div[1]/div[2]/div[4]/div/ul/li[7]/span[1]')
hat1.click()

In [92]:
for i in range(0,100):
    driver.execute_script("window.scrollBy(0,5000)")
    driver.execute_script("window.scrollBy(0,-500)")

In [60]:
cpe_url = []
cpe = driver.find_elements_by_xpath('//a[@id="linkToDetails"]')

for i in cpe:
    cpe_url.append(i.get_attribute('href'))
len(cpe_url)

20

In [61]:
cprice = []
cyear = []
cmake = []
cmodel = []
cfuel = []
ctrans = []
clocation = []
cmile = []
ccolor = []
cowner =[]
cengine = []
cseating = []

for link in cpe_url:
    driver.get(link)
    time.sleep(3)
    try:
        pri = driver.find_element_by_xpath('//p[@class="used-actual"]')
        cprice.append(pri.text.replace('â‚¹','').replace('Lakh',''))
    except NoSuchElementException:
        cprice.append('-')
        
    try:
        yea = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[2]//div[2]')
        cyear.append(yea.text)
    except NoSuchElementException:
        cyear.append('-')
        
    try:
        mak = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[4]/a/span')
        cmake.append(mak.text)
    except NoSuchElementException:
        cmake.append('-')
        
    try:
        fu = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[4]//div[2]')
        cfuel.append(fu.text)
    except NoSuchElementException:
        cfuel.append('-')
        
    try:
        tr = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[5]//div[2]')
        ctrans.append(tr.text)
    except NoSuchElementException:
        ctrans.append('-')
        
    try:
        loc = driver.find_element_by_xpath('//div[@class="inline-block carlocationTxt break-word"]//p//span')
        clocation.append(loc.text)
    except NoSuchElementException:
        clocation.append('-')
        
    try:
        mod = driver.find_element_by_xpath('/html/body/div[14]/section[2]/div[1]/div[1]/div[1]/ul/li[5]/a/span')
        cmodel.append(mod.text)
    except NoSuchElementException:
        cmodel.append('-')
        
    try:
        mil = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[3]//div[2]')
        cmile.append(mil.text.replace(',','').replace('km',''))
    except NoSuchElementException:
        cmile.append('-')

    try:
        col = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[7]//div[2]')
        ccolor.append(col.text)
    except NoSuchElementException:
        ccolor.append('-')

    try:
        own = driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]//li[9]//div[2]')
        cowner.append(own.text)
    except NoSuchElementException:
        cowner.append('-')
    time.sleep(2)

    try:
        try:
            driver.find_element_by_xpath('//div[@class="cw-tabs cw-tabs-flex cw-tabs-inner-margin0"]//li[3]').click()
            time.sleep(2)
            eng = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[1]/div[2]')
            cengine.append(eng.text)
        except NoSuchElementException:
            cengine.append('-')
    except ElementClickInterceptedException:
        cengine.append('-')
        
    try:
        sea = driver.find_element_by_xpath('//*[@id="specifications"]/div/ul/li[3]/div[4]')
        cseating.append(sea.text.replace('Person',''))
    except NoSuchElementException:
        cseating.append('-')

In [62]:
cpe_bng = pd.DataFrame({})
cpe_bng['price'] = cprice
cpe_bng['year'] = cyear
cpe_bng['make'] = cmake
cpe_bng['model'] = cmodel
cpe_bng['fuel'] = cfuel
cpe_bng['trans'] = ctrans
cpe_bng['location'] = clocation
cpe_bng['mile'] = cmile
cpe_bng['color'] = ccolor
cpe_bng['owner'] = cowner
cpe_bng['engine'] = cengine
cpe_bng['seating'] = cseating
cpe_bng['Body'] = 'coupe/convertible'
cpe_bng.head()

,price,year,make,model,fuel,trans,location,mile,color,owner,engine,seating,Body
0,30,Jun 2013,BMW,3-Series,Diesel,Automatic,Bangalore,40000,White,First,-,-,coupe/convertible
1,2.3 Crore,Jun 2017,Aston Martin,DB11,Petrol,Automatic,Bangalore,5000,Grey,First,"5198 cc, 12 Cylinders In V Shape, 4 Valves/Cyl...",4,coupe/convertible
2,27.5,Jun 2011,Audi,TT,Petrol,Manual,Bangalore,12000,White,First,-,-,coupe/convertible
3,75.95,Jun 2018,Mercedes-Benz,GLC Coupe,Petrol,Automatic,Bangalore,11500,Red,First,"2996 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",4,coupe/convertible
4,59,Oct 2015,Mercedes-Benz,SLK-Class,Petrol,Automatic,Bangalore,3256,Grey,First,"3498 cc, 6 Cylinders In V Shape, 4 Valves/Cyli...",2,coupe/convertible

In [63]:
cars_bng = pd.concat([hatch_bng,suv_bng,sdn_bng,van_bng,cpe_bng], axis = 0, ignore_index =True)

In [64]:
cars_bng.to_excel('cars_bng.xlsx', index = False)